### ISSUE TITLE
imgやvideoが表示されない問題を解決する

### ISSUE THREAD

**Issue by hiyakake** [LavP/ar-step#40]
A-frameの `<style>` によって `a-antity img|video` に `display:none` が指定されているのが原因だった。

なのでCSSでこのルールを上回るものを入れる

mian.css
``` css
#ui_2d img,
#ui_2d video{
    display: inherit;
}
```
